Controllers/BlogCommentController.cs
using System;
using System.Threading.Tasks;
using Blog.Areas.Identity.Data;
using Blog.Contracts;
using Blog.Data.Repositories;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class BlogCommentController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ApplicationDbContext _db;
        private readonly IPostService _postService;
        public BlogCommentController(ApplicationDbContext dbContext ,IPostRepository postRepository, IPostService postService)
        {
            _db = dbContext;
            _postRepository = postRepository;
            _postService = postService;
        }
        
        // GET
        public async Task<IActionResult> Show(string slug)
        {
            Post post = await _postRepository.FindWithCategoryAuthorAndCommentsForSlug(slug);
            ShowBlogViewModel viewModel = new ShowBlogViewModel()
            {
                Post = post
            };

            return View(viewModel);
        }
      
        [HttpPost][ValidateAntiForgeryToken][ActionName("Show")]
        public async Task<IActionResult> CreateComment(AddCommentInputModel model)
        {
            long postId = model.PostId;
            if (!await _postRepository.AnyForId(postId))
                return NotFound();

            if (!ModelState.IsValid)
            {
                // var test = await _postService.GetShowBlogViewModel(model, postId);
                
                return View( await _postService.GetShowBlogViewModel(model, postId));
            }

            Comment comment = new Comment()
            {
                Name = model.Name,
                Email = model.Email,
                Description = model.Description,
                PostId = postId
            };

            try
            {
                _db.Add(comment);
                await _db.SaveChangesAsync();
                TempData["successMessage"] = "successfully  added new comment";
                
                return RedirectToAction("show", "Post");
            }
            catch (Exception e)
            {
                TempData["failMessage"] = "failed to add new comment";
                return View( await _postService.GetShowBlogViewModel(model, postId));
                //"/Views/BlogComment/show.cshtml",
            }
        }
    }
}

Controllers/BlogController.cs
using System.Threading.Tasks;
using Blog.Data.Repositories;
using Blog.Models;
using Blog.Services;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class BlogController : Controller
    {
        private readonly IPostRepository _postRepository;

        public BlogController(IPostRepository postRepository)
        {
            _postRepository = postRepository;
        }
        
        // GET
        
        public async Task<IActionResult> Index(int pageNo = 1)
        {
            Pagination<Post> allPosts = await _postRepository.Paginate(pageNo, 1);
            return View(allPosts);
        }

        //
        // public async Task<IActionResult> Show(string slug)
        // {
        //     Post post = await _postRepository.FindWithCategoryAuthorAndCommentsForSlug(slug);
        //     ShowBlogViewModel viewModel = new ShowBlogViewModel()
        //     {
        //         Post = post
        //     };
        //
        //     return View(viewModel);
        // }
    }
}

Controllers/CommentController.cs
using System;
using System.Threading.Tasks;
using Blog.Areas.Identity.Data;
using Blog.Contracts;
using Blog.Data.Repositories;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
 
    public class CommentController : Controller
    {

        
        
 

         
    }
}

Views/BlogComment/show.cshtml
@model ShowBlogViewModel

@{
    // Layout = null;
    ViewData["Title"] = "blog list";
}

<h1>Blog</h1>
<partial name="_MessagePartial"/>

<p class="text-right">
    <a asp-controller="Blog" asp-action="Index" > All Blogs</a>
</p>

<div class="row">
	<div class="col-md-8 offset-md-2">
		<h1>Title : @Model.Post.Title</h1>
		<h3>Published At : @Model.Post.CreatedAt</h3>
		<h3>Author : @Model.Post.Author.UserName</h3>
		<p>@Model.Post.Body </p>
		<hr>
		<strong>Posted in: </strong> @Model.Post.Category.Name
	</div>
</div>

	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="comment-title top-spacing-30">
				<h3><span class="glyphicon glyphicon-comment"></span>@Model.Post.Comments.Count comments</h3>
			</div>
			
			@for(int i = 0; i < Model.Post.Comments.Count; i++)
			{
				Comment comment = Model.Post.Comments[i];
				<div class="media top-spacing-20">

					<img src="https://www.gravatar.com/avatar/@(Model.AddCommentInputModel.Email)?s=50&d=monsterid"  class=" mr-3 author-image" alt="aaaa">

					<div class="media-body">
						<h4 class="mt-0">@comment.Name</h4>
						<p class="author-time"> @comment.CreatedAt</p>
						<div class="comment-content">
							@comment.Description
						</div>
					</div>

				</div>

			}
			</div>
		</div>

<div class="row">
	<div class="col-md-8 offset-md-2">
		@* <form asp-controller="Comment" asp-action="Create"> *@
		<form asp-controller="BlogComment" asp-action="show" asp-route-postId="@Model.Post.PostId">
			<div asp-validation-summary="All" class="text-danger"></div>
			<div class="row">
				<div class="col-md-6 form-group">
					<label asp-for="AddCommentInputModel.Name" class="control-label"></label>
					<input asp-for="AddCommentInputModel.Name" class="form-control"/>
				</div>
				<div class="col-md-6 form-group">
					<label asp-for="AddCommentInputModel.Email" class="control-label"></label>
					<input asp-for="AddCommentInputModel.Email" class="form-control"/>
				</div>
			</div>

			<div class="form-group">
				<label asp-for="AddCommentInputModel.Description" class="control-label"></label>
				<textarea asp-for="AddCommentInputModel.Description" rows="5" class="form-control"></textarea>
				<label>Comment:</label>
			</div>

			<div class="form-group">
				<input asp-for="AddCommentInputModel.PostId" type="hidden"  class="form-control"/>
				<label>Comment:</label>
			</div>
			<input type="submit" name="submit" class="btn btn-success btn-block">
		</form>
	</div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}