Controllers/BlogController.cs
using System.Threading.Tasks;
using Blog.Data.Repositories;
using Blog.Models;
using Blog.Services;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class BlogController : Controller
    {
        private readonly IPostRepository _postRepository;

        public BlogController(IPostRepository postRepository)
        {
            _postRepository = postRepository;
        }
        
        // GET
        
        public async Task<IActionResult> Index(int pageNo = 1)
        {
            Pagination<Post> allPosts = await _postRepository.Paginate(pageNo, 1);
            return View(allPosts);
        }

        //
        // public async Task<IActionResult> Show(string slug)
        // {
        //     Post post = await _postRepository.FindWithCategoryAuthorAndCommentsForSlug(slug);
        //     ShowBlogViewModel viewModel = new ShowBlogViewModel()
        //     {
        //         Post = post
        //     };
        //
        //     return View(viewModel);
        // }
    }
}

Controllers/CommentController.cs
using System;
using System.Threading.Tasks;
using Blog.Areas.Identity.Data;
using Blog.Contracts;
using Blog.Data.Repositories;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
 
    public class CommentController : Controller
    {

        
        
 

         
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Blog.Areas.Identity.Data;
using Blog.Data.Repositories;
using Blog.Models;
using Blog.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace Blog.Controllers
{
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ITagRepository _tagRepository;
        private readonly IPostRepository _postRepository;
      
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        
        public PostController(ApplicationDbContext context, ICategoryRepository categoryRepository, ITagRepository tagRepository, IPostRepository postRepository,IConfiguration config, IWebHostEnvironment hostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _db = context;
            _categoryRepository = categoryRepository;
            _tagRepository = tagRepository;
            _postRepository = postRepository;
            _hostEnvironment = hostEnvironment;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index(int pageNo = 1)
        {
            //List<Post> allPosts = await _postRepository.All();
            Pagination<Post> allPosts = await _postRepository.Paginate(pageNo, 1);
            
            
            //return Ok(await _postRepository.Paginate(HttpContext.Request));
            
            return View(allPosts);
        }

        public async Task<IActionResult> Create()
        {
            List<SelectListItem> categories = (await _categoryRepository.All())
                .ConvertAll(category => new SelectListItem()
                {
                    Value = category.CategoryId.ToString(),
                    Text = category.Name
                });

            List<SelectListItem> tags = (await _tagRepository.All())
                .ConvertAll(tag => new SelectListItem()
                {
                    Value = tag.TagId.ToString(),
                    Text = tag.Name
                });
            
            AddPostViewModel addPostViewModel = new AddPostViewModel()
            {
                Categories = categories,
                Tags = tags
            };
            
            return View(addPostViewModel);
        }
        
        [HttpPost][ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddPostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                await AddViewDataForPost(model);
                return View(model);
            }
            
            
            //start: upload image
            string uuid = Guid.NewGuid().ToString();
            string originalExt = Path.GetExtension(model.Image.FileName);
            string fileName = $"{uuid}.{originalExt}";
            
            string imageDirectoryName = "images";
            string imageDirectoryPath = Path.Combine(_hostEnvironment.WebRootPath, imageDirectoryName);
            string imagePath = Path.Combine(imageDirectoryPath, fileName);

            if (!Directory.Exists(imageDirectoryPath))
            {
                try
                {
                    Directory.CreateDirectory(imageDirectoryPath);
                }
                catch (Exception e)
                {
                    TempData["failMessage"] = $"failed to create new post {model.Title}";
                    await AddViewDataForPost(model);
                    return View(model);
                }
            }
            
            using (FileStream fileStream = new FileStream(imagePath, FileMode.Create))
            { 
                await model.Image.CopyToAsync(fileStream);
            }
            //end: upload image

            Post post = new Post()
            {
                Title = model.Title,
                Slug = model.Slug,
                Image = Path.Combine(imageDirectoryName, fileName),
                Body = model.Body,
                CategoryId = model.CategoryId,
                AuthorId = _userManager.GetUserId(HttpContext.User)
            };

            if (model.TagIds != null && model.TagIds.Any())
            {
                post.PostTags = new List<PostTag>();
                foreach (long tagId in model.TagIds)
                {
                    post.PostTags.Add(new PostTag()
                    {
                        TagId = tagId
                    });
                }
            }
            
            _db.Add(post);
            
            /*
             * todo : db transaction is automatically used for SaveChanges. so no need. only if  _db.SaveChangesAsync is called more than once, manually call _db.Database.BeginTransaction()
             */
            
            try
            {
                await _db.SaveChangesAsync();
                TempData["successMessage"] = $"successfully created new post `{post.Title}`";
                return RedirectToAction(nameof(Index));
              
            }
            catch (Exception)
            {
                TempData["failMessage"] = $"failed to create new post {model.Title}";
                if (await _postRepository.AnyForSlug(model.Slug))
                    TempData["failMessage"] = "slug already used";
                
                await AddViewDataForPost(model);
                return View(model);
            }
          
        }


        public int show(int postId)
        {
            return postId;
        }
        
        
        private async Task AddViewDataForPost(AddPostViewModel model)
        {
            model.Categories = (await _categoryRepository.All())
                .ConvertAll(category => new SelectListItem()
                {
                    Value = category.CategoryId.ToString(),
                    Text = category.Name
                });

            model.Tags = (await _tagRepository.All())
                .ConvertAll(tag => new SelectListItem()
                {
                    Value = tag.TagId.ToString(),
                    Text = tag.Name
                });
        }
    }
        
    //     [HttpPost][ValidateAntiForgeryToken]
    //     public async Task<IActionResult> Create(AddPostViewModel addPostViewModel)
    //     {
    //         
    //     }
    // }
}

Views/Blog/Index.cshtml
@model Blog.Contracts.IPagination<Post>

@{
    // Layout = null;
    ViewData["Title"] = "blog list";
}

<h1>Categories List</h1>
<partial name="_MessagePartial"/>
<p class="text-right">
    <a asp-controller="Post" asp-action="Create" > Add New Category</a>
</p>

@for(int i = 0; i < Model.Items.Count; i++ )
{
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2>  <a asp-controller="BlogComment" asp-action="show" asp-route-slug="@Model[i].Slug"> @Model[i].Title </a> </h2>
            <h6> published: @Model[i].CreatedAt </h6>
            <p>@Model[i].Body</p>
            <p>@Model[i].Body.Substring(0, @Model[i].Body.Length >= 300 ? 300 : @Model[i].Body.Length) @if (Model[i].Body.Length > 300){<span> ... </span>}</p>
            @* <a href="{{ route('blog.single', $post->slug) }}" class="">read more</a> *@
            <hr>
        </div>
    </div>
}

@if (Model.Last > 1)
{
    <p class="center-block">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a href="@Model.FirstPageUri" class="page-link btn btn-link " role="button" aria-pressed="true">First</a></li>
                @if (Model.PreviousPageUri == null)
                {
                    <li class="page-item"><a href="#" class="page-link btn btn-link disabled" role="button" aria-pressed="true">Previous</a></li>
                }
                else
                {
                    <li class="page-item"><a href="@Model.PreviousPageUri" class="page-link btn btn-link " role="button" aria-pressed="true">Previous</a></li>
                }
                    
                <li class="page-item">  <a href="#" class="page-link btn btn-link disabled" role="button" aria-pressed="true">@Model.Current</a></li>

                @if (Model.NextPageUri == null)
                {
                    <li class="page-item">
                        <a href="#" class="page-link btn btn-link disabled" role="button" aria-pressed="true">Next</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a href="@Model.NextPageUri" class="page-link btn btn-link " role="button" aria-pressed="true">Next</a>
                    </li>
                }
                
                <li class="page-item">
                    <a href="@Model.LastPageUri" class="page-link btn btn-link " role="button" aria-pressed="true">Last</a>
                </li>
            </ul>
        </nav>
    </p>
}

Views/Blog/show.cshtml
@model ShowBlogViewModel

@{
    // Layout = null;
    ViewData["Title"] = "blog list";
}

<h1>Blog</h1>
<partial name="_MessagePartial"/>

<p class="text-right">
    <a asp-controller="Blog" asp-action="Index" > All Blogs</a>
</p>

<div class="row">
	<div class="col-md-8 offset-md-2">
		<h1>Title : @Model.Post.Title</h1>
		<h3>Published At : @Model.Post.CreatedAt</h3>
		<h3>Author : @Model.Post.Author.UserName</h3>
		<p>@Model.Post.Body </p>
		<hr>
		<strong>Posted in: </strong> @Model.Post.Category.Name
	</div>
</div>

	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="comment-title top-spacing-30">
				<h3><span class="glyphicon glyphicon-comment"></span>@Model.Post.Comments.Count comments</h3>
			</div>
			
			@for(int i = 0; i < Model.Post.Comments.Count; i++)
			{
				Comment comment = Model.Post.Comments[i];
				<div class="media top-spacing-20">

					<img src="https://www.gravatar.com/avatar/@(Model.AddCommentInputModel.Email)?s=50&d=monsterid"  class=" mr-3 author-image" alt="aaaa">

					<div class="media-body">
						<h4 class="mt-0">@comment.Name</h4>
						<p class="author-time"> @comment.CreatedAt</p>
						<div class="comment-content">
							@comment.Description
						</div>
					</div>

				</div>

			}
			</div>
		</div>

<div class="row">
	<div class="col-md-8 offset-md-2">
		@* <form asp-controller="Comment" asp-action="Create"> *@
		<form>
			<div asp-validation-summary="All" class="text-danger"></div>
			<div class="row">
				<div class="col-md-6 form-group">
					<label asp-for="AddCommentInputModel.Name" class="custom-control-label"></label>
					<input asp-for="AddCommentInputModel.Name" class="form-control"/>
				</div>
				<div class="col-md-6 form-group">
					<label asp-for="AddCommentInputModel.Email" class="custom-control-label"></label>
					<input asp-for="AddCommentInputModel.Email" class="form-control"/>
				</div>
			</div>

			<div class="form-group">
				<label asp-for="AddCommentInputModel.Description" class="custom-control-label"></label>
				<textarea asp-for="AddCommentInputModel.Description" rows="5" class="form-control"></textarea>
				<label>Comment:</label>
			</div>
			<input type="submit" name="submit" class="btn btn-success btn-block">
		</form>
	</div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}